# Generated by Django 5.2.3 on 2025-06-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookClub",
            fields=[
                ("url", models.TextField(primary_key=True, serialize=False)),
                ("author", models.CharField(max_length=255)),
                ("book", models.CharField(max_length=500)),
                ("date", models.DateField()),
                ("integration_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "book_club",
            },
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "integration",
            },
        ),
    ]
