app = "the-green-papaya-api"
primary_region = "ord"

[build]

[env]
DEBUG = "false"
ALLOWED_HOSTS = "the-green-papaya-api.fly.dev"


[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/admin/"

[processes]
app = "gunicorn --bind 0.0.0.0:8000 api.wsgi:application"

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1